CREATE DATABASE IF NOT EXISTS SE104;

USE SE104;

CREATE TABLE CAUTHU (
	MaCauThu	CHAR(10) PRIMARY KEY NOT NULL,
	TenCauThu	NVARCHAR(50) NOT NULL,
	NgaySinh	DATE NOT NULL,
	QuocTich	NVARCHAR(20) NOT NULL,
	LoaiCauThu	BIT NOT NULL,
	ViTri	NVARCHAR(20) NOT NULL,
	ChieuCao	FLOAT NOT NULL,
	CanNang	FLOAT NOT NULL,
	SoAo TINYINT(2) UNSIGNED NOT NULL
);

CREATE TABLE DOIBONG (
	MaDoiBong CHAR(10) PRIMARY KEY NOT NULL,
	TenDoiBong NVARCHAR(50) NOT NULL,
	CoQuanChuQuan NVARCHAR(50) NOT NULL,
	ThanhPhoTrucThuoc NVARCHAR (50) NOT NULL,
	MaSan CHAR(10) NOT NULL,
	HLV NVARCHAR(50) NOT NULL,
	ThongTin NVARCHAR(1000) NOT NULL,
	Logo NVARCHAR(100) NOT NULL
);

CREATE TABLE SANTHIDAU (
	MaSan CHAR(10) PRIMARY KEY NOT NULL,
	TenSan NVARCHAR(30) NOT NULL,
	DiaChiSan NVARCHAR(50) NOT NULL,
	SucChua	INT NOT NULL,
	TieuChuan TINYINT NOT NULL
);

CREATE TABLE BIENNHAN (
	MaLePhi	CHAR(10) PRIMARY KEY NOT NULL,
	MaDoiBong	CHAR(10) NOT NULL,
	SoTien DECIMAL NOT NULL,
	NgayBatDau	DATE NOT NULL,
	NgayHetHan	DATE NOT NULL,
	NgayThanhToan	DATE NOT NULL,
	TinhTrang	BIT NOT NULL
);

CREATE TABLE MUAGIAI (
	MaMuaGiai CHAR(10) PRIMARY KEY NOT NULL,
	TenMuaGiai NVARCHAR(50) NOT NULL,
	NgayBatDau DATE NOT NULL,
	NgayKetThuc DATE NOT NULL
);

CREATE TABLE MG_DB_CT (
	MaMuaGiai CHAR(10) NOT NULL,
	MaDoiBong CHAR(10) NOT NULL,
	MaCauThu CHAR(10) NOT NULL
);

CREATE TABLE VONGDAU (
	MaVongDau CHAR(10) PRIMARY KEY NOT NULL,
	MaMuaGiai CHAR(10) NOT NULL,
	LuotDau	BIT NOT NULL,
	SoThuTu	TINYINT NOT NULL,
	NgayBatDau DATE NOT NULL,
	NgayKetThuc DATE NOT NULL
);

CREATE TABLE TRANDAU (
	MaTranDau CHAR(10) PRIMARY KEY NOT NULL,
	MaVongDau CHAR(10) NOT NULL,
	MaDoiBongNha CHAR(10) NOT NULL,
	MaDoiBongKhach	CHAR(10) NOT NULL,
	NgayThiDau DATE NOT NULL,
	GioThiDau TIME NOT NULL,
	MaSan CHAR(10) NOT NULL,
    BanThangDoiNha INT NOT NULL,
	BanThangDoiKhach INT NOT NULL
);

CREATE TABLE BANTHANG (
	MaBanThang	CHAR(10) PRIMARY KEY NOT NULL,
	MaTranDau	CHAR(10) NOT NULL,
	MaDoiBong	CHAR(10) NOT NULL,
	MaCauThu	CHAR(10) NOT NULL,
	MaLoaiBanThang	CHAR(10) NOT NULL,
	ThoiDiem	TIME NOT NULL
);

CREATE TABLE LOAIBANTHANG (
	MaLoaiBanThang CHAR(10) PRIMARY KEY NOT NULL,
	TenLoaiBanThang NVARCHAR (20) NOT NULL,
	MoTa NVARCHAR (50) NOT NULL
);

CREATE TABLE BANGXEPHANG (
	MaMuaGiai CHAR(10) NOT NULL,
	MaVongDau CHAR (10) NOT NULL,
	MaDoiBong CHAR(10) NOT NULL,
	SoTran TINYINT NOT NULL,
	SoTranThang	TINYINT NOT NULL,
	SoTranHo TINYINT NOT NULL,
	SoTranThua TINYINT NOT NULL,
	SoBanThang TINYINT NOT NULL,
	SoBanThua TINYINT NOT NULL,
	HieuSo TINYINT NOT NULL,
	Diem TINYINT NOT NULL
);

CREATE TABLE UT_XEPHANG (
	MaMuaGiai CHAR(10) PRIMARY KEY NOT NULL,
	MaLoaiUT NVARCHAR (50) NOT NULL,
	MucDoUT TINYINT NOT NULL
);

CREATE TABLE LOAIUUTIEN (
	MaLoaiUT CHAR(10) PRIMARY KEY NOT NULL,
	TenLoaiUT NVARCHAR (50) NOT NULL
);

CREATE TABLE VUAPHALUOI (
	MaCauThu CHAR(10) PRIMARY KEY NOT NULL,
	MaMuaGiai CHAR(10) NOT NULL,
	SoTran CHAR (10) NOT NULL,
	SoBanThang TIME NOT NULL
);

CREATE TABLE THEPHAT (
	MaThePhat CHAR(10) PRIMARY KEY NOT NULL,
	MaTranDau CHAR (10) NOT NULL,
	MaCauThu CHAR (10) NOT NULL,
	MaLoaiThePhat CHAR(10) NOT NULL,
	ThoiGian TIME NOT NULL,
	LyDo NVARCHAR(50) NOT NULL
);

CREATE TABLE LOAITHEPHAT (
	MaLoaiThePhat CHAR(10) PRIMARY KEY NOT NULL,
	TenLoaiThePhat NVARCHAR(10) NOT NULL,
	MoTa NVARCHAR(50) NOT NULL
);

CREATE TABLE DSTHEPHAT (
	MaCauThu CHAR(10) PRIMARY KEY NOT NULL,
	MaVongDau NVARCHAR(10) NOT NULL,
	SoTheVang CHAR(10) NOT NULL,
	SoTheDo CHAR(10) NOT NULL,
	TinhTrangThiDau BIT NOT NULL
);

CREATE TABLE LICHSUGIAIDAU (
	MaDoiBong CHAR(10) PRIMARY KEY NOT NULL,
	SoLanThamGia TINYINT NOT NULL,
	SoTranThang TINYINT NOT NULL,
	SoLanVoDich TINYINT NOT NULL,
	SoLanAQuan TINYINT NOT NULL,
	SoLanHangBa TINYINT NOT NULL
);

CREATE TABLE THANHTICH (
	MaDoiBong	CHAR(10) PRIMARY KEY NOT NULL,
	MaMuaGiai	CHAR(10) NOT NULL,
	SoTranDaThiDau	TINYINT NOT NULL,
	SoTranThang	TINYINT NOT NULL,
	SoTranHoa	TINYINT NOT NULL,
	SoTranThua	TINYINT NOT NULL,
	XepHang	CHAR(10) NOT NULL
);

CREATE TABLE THAMSO(
	SucChuaToiThieu INT NOT NULL,
	TieuChuanToiThieu TINYINT NOT NULL,
	TuoiToiThieu TINYINT NOT NULL,
	TuoiToiDa TINYINT NOT NULL,
	SoLuongCauThuToiThieu TINYINT NOT NULL,
	SoLuongCauThuToiDa TINYINT NOT NULL,
	SoCauThuNgoaiToiDa TINYINT NOT NULL,
	LePhi INT NOT NULL,
	ThoiDiemGhiBanToiDa INT NOT NULL,
	DiemThang TINYINT NOT NULL,
	DiemHoa TINYINT NOT NULL,
	DiemThua TINYINT NOT NULL
);

-- ADD PRIMARY KEY -- 
ALTER TABLE MG_DB_CT
ADD CONSTRAINT PK_MG_DB_CT PRIMARY KEY (MaMuaGiai, MaDoiBong, MaCauThu);

ALTER TABLE BANGXEPHANG
ADD CONSTRAINT PK_BANGXEPHANG PRIMARY KEY (MaMuaGiai, MaVongDau, MaDoiBong);

ALTER TABLE UT_XEPHANG
ADD CONSTRAINT PK_UT_XEPHANG PRIMARY KEY (MaMuaGiai, MaLoaiUT);

ALTER TABLE VUAPHALUOI
ADD CONSTRAINT PK_VUAPHALUOI PRIMARY KEY (MaCauThu, MaMuaGiai);

ALTER TABLE DSTHEPHAT
ADD CONSTRAINT PK_DSTHEPHAT PRIMARY KEY (MaCauThu, MaVongDau);

ALTER TABLE THANHTICH
ADD CONSTRAINT PK_THANHTICH PRIMARY KEY (MaDoiBong, MaMuaGiai);

-- ADD FOREIGN KEY -- 
ALTER TABLE DOIBONG
ADD CONSTRAINT FK_DOIBONG_SAN FOREIGN KEY (MaSan) REFERENCES SANTHIDAU(MaSan);

ALTER TABLE BIENNHAN
ADD CONSTRAINT FK_BIENNHAN_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong);

ALTER TABLE MG_DB_CT
ADD CONSTRAINT FK_MG_DB_CT_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai),
ADD CONSTRAINT FK_MG_DB_CT_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong),
ADD CONSTRAINT FK_MG_DB_CT_CAUTHU FOREIGN KEY (MaCauThu) REFERENCES CAUTHU(MaCauThu);

ALTER TABLE VONGDAU
ADD CONSTRAINT FK_VONGDAU_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai);

ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_VONGDAU FOREIGN KEY (MaVongDau) REFERENCES VONGDAU(MaVongDau),
ADD CONSTRAINT FK_TRANDAU_DOIBONGNHA FOREIGN KEY (MaDoiBongNha) REFERENCES DOIBONG(MaDoiBong),
ADD CONSTRAINT FK_TRANDAU_DOIBONGKHACH FOREIGN KEY (MaDoiBongKhach) REFERENCES DOIBONG(MaDoiBong),
ADD CONSTRAINT FK_TRANDAU_SAN FOREIGN KEY (MaSan) REFERENCES SANTHIDAU(MaSan);

ALTER TABLE BANTHANG
ADD CONSTRAINT FK_BANTHANG_TRANDAU FOREIGN KEY (MaTranDau) REFERENCES TRANDAU(MaTranDau),
ADD CONSTRAINT FK_BANTHANG_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong),
ADD CONSTRAINT FK_BANTHANG_CAUTHU FOREIGN KEY (MaCauThu) REFERENCES CAUTHU(MaCauThu),
ADD CONSTRAINT FK_BANTHANG_LOAIBANTHANG FOREIGN KEY (MaLoaiBanThang) REFERENCES LOAIBANTHANG(MaLoaiBanThang);

ALTER TABLE BANGXEPHANG
ADD CONSTRAINT FK_BANGXEPHANG_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai),
ADD CONSTRAINT FK_BANGXEPHANG_VONGDAU FOREIGN KEY (MaVongDau) REFERENCES VONGDAU(MaVongDau),
ADD CONSTRAINT FK_BANGXEPHANG_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong);

ALTER TABLE UT_XEPHANG
ADD CONSTRAINT FK_UT_XEPHANG_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai),
ADD CONSTRAINT FK_UT_XEPHANG_LOAIUT FOREIGN KEY (MaLoaiUT) REFERENCES LOAIUUTIEN(MaLoaiUT);

ALTER TABLE VUAPHALUOI
ADD CONSTRAINT FK_VUAPHALUOI_CAUTHU FOREIGN KEY (MaCauThu) REFERENCES CAUTHU(MaCauThu),
ADD CONSTRAINT FK_VUAPHALUOI_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai);

ALTER TABLE THEPHAT
ADD CONSTRAINT FK_THEPHAT_TRANDAU FOREIGN KEY (MaTranDau) REFERENCES TRANDAU(MaTranDau),
ADD CONSTRAINT FK_THEPHAT_CAUTHU FOREIGN KEY (MaCauThu) REFERENCES CAUTHU(MaCauThu),
ADD CONSTRAINT FK_THEPHAT_LOAITHEPHAT FOREIGN KEY (MaLoaiThePhat) REFERENCES LOAITHEPHAT(MaLoaiThePhat);

ALTER TABLE DSTHEPHAT
ADD CONSTRAINT FK_DSTHEPHAT_CAUTHU FOREIGN KEY (MaCauThu) REFERENCES CAUTHU(MaCauThu),
ADD CONSTRAINT FK_DSTHEPHAT_VONGDAU FOREIGN KEY (MaVongDau) REFERENCES VONGDAU(MaVongDau);

ALTER TABLE LICHSUGIAIDAU
ADD CONSTRAINT FK_LICHSUGIAIDAU_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong);

ALTER TABLE THANHTICH
ADD CONSTRAINT FK_THANHTICH_DOIBONG FOREIGN KEY (MaDoiBong) REFERENCES DOIBONG(MaDoiBong),
ADD CONSTRAINT FK_THANHTICH_MUAGIAI FOREIGN KEY (MaMuaGiai) REFERENCES MUAGIAI(MaMuaGiai);
