let availableTeams = [
  {
    id: 1,
    name: "Hà Nội FC",
    city: "Hà Nội",
    coach: "Gad",
    stadiumId: 1,
    capacity: 22500,
    standard: 5,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/e/eb/Hanoi_FC.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hà Nội",
    season: null,
  },
  {
    id: 2,
    name: "Viettel FC",
    city: "Hà Nội",
    coach: "Tăng Nhất",
    stadiumId: 1,
    capacity: 22500,
    standard: 4,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/d/d5/Viettel_FC_logo.png/1200px-Viettel_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Viettel",
    season: null,
  },
  {
    id: 3,
    name: "Hoàng Anh Gia Lai",
    city: "Pleiku",
    coach: "Faigar",
    stadiumId: 2,
    capacity: 12000,
    standard: 4,
    home_kit_image: null,
    away_kit_image: null,
    third_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/7/7d/Hoang_Anh_Gia_Lai_FC_logo.png/1200px-Hoang_Anh_Gia_Lai_FC_logo.png",
    description: "Câu lạc bộ bóng đá Hoàng Anh Gia Lai",
    season: null,
  },
  {
    id: 4,
    name: "Becamex Bình Dương",
    city: "Thủ Dầu Một",
    coach: "Superman",
    stadiumId: 3,
    capacity: 18250,
    standard: 3,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/0/07/Becamex_Binh_Duong_FC_logo.png/1200px-Becamex_Binh_Duong_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Becamex Bình Dương",
    season: null,
  },
  {
    id: 5,
    name: "Hải Phòng",
    city: "Hải Phòng",
    coach: "tslnh",
    stadiumId: 4,
    capacity: 26000,
    standard: 4,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/8/85/Hai_Phong_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hải Phòng",
    season: null,
  },
  {
    id: 6,
    name: "Đông Á Thanh Hóa",
    city: "Thanh Hóa",
    coach: "Popovic",
    stadiumId: 5,
    capacity: 15000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/e/e7/%C4%90%C3%B4ng_A_Thanh_H%C3%B3a_FC_logo.svg/1200px-%C4%90%C3%B4ng_A_Thanh_H%C3%B3a_FC_logo.svg.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Đông Á Thanh Hóa",
    season: null,
  },
  {
    id: 7,
    name: "Sông Lam Nghệ An",
    city: "Vinh",
    coach: "Phan Như Thuật",
    stadiumId: 6,
    capacity: 18000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/a/a8/Song_Lam_Nghe_An_FC_logo.png/1200px-Song_Lam_Nghe_An_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Sông Lam Nghệ An",
    season: null,
  },
  {
    id: 8,
    name: "Nam Định FC",
    city: "Nam Định",
    coach: "Vũ Hồng Việt",
    stadiumId: 7,
    capacity: 20000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/c/c7/Nam_%C4%90%E1%BB%8Bnh_FC_logo.png/1200px-Nam_%C4%90%E1%BB%8Bnh_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Nam Định",
    season: null,
  },
];

let seasons = [
  {
    id: "2023-2024",
    name: "Mùa giải 2023-2024",
    startDate: "2023-08-01",
    endDate: "2024-05-30",
    teams: [1, 2, 3, 4, 5, 6, 7, 8],
    rounds: [
      {
        roundId: "2023-2024-ROUND1",
        name: "Lượt đi",
        startDate: "2023-08-05",
        endDate: "2023-08-07",
      },
      {
        roundId: "2023-2024-ROUND2",
        name: "Lượt về",
        startDate: "2023-08-12",
        endDate: "2023-08-14",
      },
    ],
  },
  {
    id: "2024-2025",
    name: "Mùa giải 2024-2025",
    startDate: "2024-08-01",
    endDate: "2025-05-30",
    teams: [1, 2, 3, 4, 5, 6, 7, 8],
    rounds: [],
  },
  {
    id: "2022-2023",
    name: "Mùa giải 2022-2023",
    startDate: "2022-08-01",
    endDate: "2023-05-30",
    teams: [1, 2, 3, 4, 5],
    rounds: [
      {
        roundId: "2022-2023-ROUND1",
        name: "Lượt đi",
        startDate: "2022-08-05",
        endDate: "2022-08-07",
      },
      {
        roundId: "2022-2023-ROUND2",
        name: "Lượt về",
        startDate: "2022-08-12",
        endDate: "2022-08-14",
      },
    ],
  },
];

let players = {
  "2023-2024": {
    1: [
      {
        id: 1,
        name: "Văn Quyết",
        dob: "1991-06-27", // Corrected date of birth
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Tây", // More specific birthplace
        height: 173, // Corrected height
        weight: 70, // Corrected weight
        bio: "Đội trưởng và là một trong những cầu thủ xuất sắc nhất của Hà Nội FC.",
        playerType: "Trong nước",
      },
      {
        id: 4,
        name: "Đỗ Hùng Dũng",
        dob: "1993-09-08", // Corrected date of birth
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Gia Lâm, Hà Nội",
        height: 176,
        weight: 72,
        bio: "Tiền vệ trung tâm mạnh mẽ và có khả năng điều tiết trận đấu tốt.",
        playerType: "Trong nước",
      },
      {
        id: 15, // Added missing player
        name: "Geovane",
        dob: "1994-09-05",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Rio de Janeiro",
        height: 175,
        weight: 74,
        bio: "Tiền đạo ngoại binh kỹ thuật.",
        playerType: "Nước ngoài",
      },
      {
        id: 16, // Added missing player
        name: "Tuấn Hải",
        dob: "1998-05-29",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Thái Bình",
        height: 180,
        weight: 74,
        bio: "Tiền đạo có khả năng dứt điểm tốt.",
        playerType: "Trong nước",
      },
      {
        id: 17,
        name: "Lucao",
        dob: "1991-12-23",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Brasília",
        height: 183,
        weight: 80,
        bio: "Tiền đạo ngoại binh mạnh mẽ.",
        playerType: "Nước ngoài",
      },
      {
        id: 18,
        name: "Marcao Silva",
        dob: "1994-05-16",
        position: "Hậu vệ",
        nationality: "Brazil",
        birthplace: "Rio de Janeiro",
        height: 186,
        weight: 82,
        bio: "Trung vệ ngoại binh chất lượng.",
        playerType: "Nước ngoài",
      },
      {
        id: 19,
        name: "Duy Mạnh",
        dob: "1996-09-29",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Đông Anh, Hà Nội",
        height: 180,
        weight: 75,
        bio: "Trung vệ mạnh mẽ và quyết đoán.",
        playerType: "Trong nước",
      }
    ],
    2: [
      {
        id: 2,
        name: "Nguyễn Đức Chiến", // Corrected name
        dob: "1998-05-20",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183, // Corrected height
        weight: 75,
        bio: "Một hậu vệ chắc chắn và có khả năng tham gia tấn công.",
        playerType: "Trong nước",
      },
      {
        id: 5,
        name: "Jeferson Elias", // Corrected name
        dob: "1999-11-10",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Rio de Janeiro",
        height: 185,
        weight: 80,
        bio: "Tiền đạo ngoại binh chất lượng với khả năng săn bàn tốt.",
        playerType: "Nước ngoài",
      },
      {
        id: 20,
        name: "Nguyễn Hoàng Đức",
        dob: "1998-01-11",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 174,
        weight: 68,
        bio: "Tiền vệ tấn công sáng tạo.",
        playerType: "Trong nước",
      }
    ],
    3: [
      {
        id: 6,
        name: "Nguyễn Công Phượng",
        dob: "1995-01-21",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Đô Lương, Nghệ An",
        height: 168,
        weight: 65,
        bio: "Tiền vệ cánh kỹ thuật và có khả năng tạo đột biến.",
        playerType: "Trong nước",
      },
      {
        id: 21,
        name: "Brandão",
        dob: "1990-05-16",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Belo Horizonte",
        height: 186,
        weight: 84,
        bio: "Tiền đạo ngoại binh mạnh mẽ và giàu kinh nghiệm.",
        playerType: "Nước ngoài",
      },
      {
        id: 22,
        name: "Tuấn Anh",
        dob: "1995-05-16",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Thái Bình",
        height: 174,
        weight: 65,
        bio: "Tiền vệ trung tâm kỹ thuật.",
        playerType: "Trong nước",
      }
    ],
    4: [
      {
        id: 7,
        name: "Quế Ngọc Hải",
        dob: "1993-05-15",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Diễn Châu, Nghệ An",
        height: 180,
        weight: 78,
        bio: "Trung vệ đội trưởng, mạnh mẽ và có khả năng lãnh đạo.",
        playerType: "Trong nước",
      },
      {
        id: 23,
        name: "Eydison",
        dob: "1988-05-26",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Curitiba",
        height: 183,
        weight: 80,
        bio: "Tiền đạo ngoại binh giàu kinh nghiệm.",
        playerType: "Nước ngoài",
      },
      {
        id: 24,
        name: "Vĩ Hào",
        dob: "2003-01-12",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Bình Dương",
        height: 170,
        weight: 65,
        bio: "Tiền đạo trẻ đầy triển vọng.",
        playerType: "Trong nước",
      }
    ],
    5: [
      {
        id: 8,
        name: "Rimario Gordon", // Corrected name
        dob: "1994-12-25",
        position: "Tiền đạo",
        nationality: "Jamaica",
        birthplace: "Kingston",
        height: 183,
        weight: 79,
        bio: "Tiền đạo chủ lực của đội, có tốc độ và khả năng dứt điểm tốt.",
        playerType: "Nước ngoài",
      },
      {
        id: 25,
        name: "Hải Huy",
        dob: "1991-06-18",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Quảng Ninh",
        height: 172,
        weight: 68,
        bio: "Tiền vệ trung tâm cần cù.",
        playerType: "Trong nước",
      },
      {
        id: 26,
        name: "Olivier Thil",
        dob: "1991-03-16",
        position: "Tiền vệ",
        nationality: "Pháp",
        birthplace: "Reims",
        height: 180,
        weight: 75,
        bio: "Tiền vệ trung tâm ngoại binh.",
        playerType: "Nước ngoài",
      }
    ],
    6: [
      {
        id: 9,
        name: "Bruno Cunha",
        dob: "1989-03-08",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Cuiabá",
        height: 188,
        weight: 85,
        bio: "Tiền đạo ngoại binh có khả năng không chiến tốt.",
        playerType: "Nước ngoài",
      },
      {
        id: 27,
        name: "Hữu Dũng",
        dob: "1993-12-28",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Thanh Hóa",
        height: 175,
        weight: 70,
        bio: "Tiền vệ phòng ngự mạnh mẽ.",
        playerType: "Trong nước",
      },
      {
        id: 28,
        name: "Gustavo Santos",
        dob: "1994-07-07",
        position: "Tiền vệ",
        nationality: "Brazil",
        birthplace: "São Paulo",
        height: 178,
        weight: 76,
        bio: "Tiền vệ tấn công ngoại binh.",
        playerType: "Nước ngoài",
      },
      {
        id: 29,
        name: "Đức Lợi",
        dob: "1991-07-09",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Thanh Hóa",
        height: 178,
        weight: 74,
        bio: "Hậu vệ cánh.",
        playerType: "Trong nước",
      }
    ],
    7: [
      {
        id: 10,
        name: "Phan Văn Đức",
        dob: "1996-04-11",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 172,
        weight: 67,
        bio: "Tiền vệ tấn công kỹ thuật và có khả năng ghi bàn.",
        playerType: "Trong nước",
      },
      {
        id: 30,
        name: "Olaha",
        dob: "1998-06-15",
        position: "Tiền đạo",
        nationality: "Nigeria",
        birthplace: "Lagos",
        height: 178,
        weight: 75,
        bio: "Tiền đạo ngoại binh nhanh nhẹn.",
        playerType: "Nước ngoài",
      },
      {
        id: 31,
        name: "Trần Đình Hoàng",
        dob: "1991-12-08",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 178,
        weight: 74,
        bio: "Hậu vệ cánh giàu kinh nghiệm.",
        playerType: "Trong nước",
      },
      {
        id: 32,
        name: "Xuân Mạnh",
        dob: "1996-01-16",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 175,
        weight: 70,
        bio: "Hậu vệ cánh.",
        playerType: "Trong nước",
      }
    ],
    8: [
      {
        id: 11,
        name: "Nguyễn Văn Toàn", // Corrected name
        dob: "1996-04-12",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 169,
        weight: 63,
        bio: "Tiền đạo có tốc độ và khả năng đi bóng lắt léo.",
        playerType: "Trong nước",
      },
      {
        id: 33,
        name: "Hendrio",
        dob: "1994-05-30",
        position: "Tiền vệ",
        nationality: "Brazil",
        birthplace: "Goiás",
        height: 176,
        weight: 72,
        bio: "Tiền vệ tấn công ngoại binh.",
        playerType: "Nước ngoài",
      },
      {
        id: 34,
        name: "Khắc Ngọc",
        dob: "1992-02-09",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 173,
        weight: 68,
        bio: "Tiền vệ trung tâm có khả năng sút xa tốt.",
        playerType: "Trong nước",
      },
      {
        id: 35,
        name: "Đinh Viết Tú",
        dob: "1992-03-12",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Nam Định",
        height: 178,
        weight: 73,
        bio: "Hậu vệ cánh.",
        playerType: "Trong nước",
      }
    ],
  },
  "2022-2023": {
    1: [
      {
        id: 3,
        name: "Nguyễn Hai Long", // Changed name to a more likely player
        dob: "2000-08-27",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Quảng Ninh",
        height: 170,
        weight: 65,
        bio: "Một tiền vệ trẻ đầy triển vọng.",
        playerType: "Trong nước",
      },
      {
        id: 12,
        name: "Mạnh Hùng", // Changed name to a more likely player
        dob: "1993-01-05",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 180,
        weight: 77,
        bio: "Trung vệ kinh nghiệm.",
        playerType: "Trong nước",
      },
      {
        id: 36,
        name: "Nguyễn Thành Chung",
        dob: "1997-09-08",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Tuyên Quang",
        height: 180,
        weight: 74,
        bio: "Trung vệ chắc chắn.",
        playerType: "Trong nước",
      }
    ],
    2: [
      {
        id: 13,
        name: "Trần Danh Trung", // Corrected name
        dob: "2000-10-03",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Huế",
        height: 175,
        weight: 70,
        bio: "Tiền đạo trẻ đầy tiềm năng.",
        playerType: "Trong nước",
      },
      {
        id: 37,
        name: "Pedro Paulo",
        dob: "1994-06-29",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Rio de Janeiro",
        height: 188,
        weight: 86,
        bio: "Tiền đạo ngoại binh mạnh mẽ.",
        playerType: "Nước ngoài",
      },
      {
        id: 38,
        name: "Bùi Tiến Dũng",
        dob: "1995-10-02",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Tĩnh",
        height: 186,
        weight: 78,
        bio: "Trung vệ có khả năng không chiến tốt.",
        playerType: "Trong nước",
      }
    ],
    3: [
      {
        id: 39,
        name: "Lương Xuân Trường",
        dob: "1995-04-28",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Tuyên Quang",
        height: 178,
        weight: 70,
        bio: "Tiền vệ trung tâm có khả năng chuyền bóng dài tốt.",
        playerType: "Trong nước",
      }
    ],
    5: [
      {
        id: 40,
        name: "Triệu Việt Hưng",
        dob: "1998-01-19",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 175,
        weight: 68,
        bio: "Tiền vệ trung tâm năng động.",
        playerType: "Trong nước",
      }
    ],
  },
};

// Khai báo availablePlayers - Danh sách cầu thủ có sẵn
let availablePlayers = Object.entries(players).reduce((acc, [season, teams]) => {
  Object.values(teams).forEach(teamPlayers => {
    teamPlayers.forEach(player => {
      acc.push({
        id: player.id,
        name: player.name,
        dob: player.dob,
        position: player.position,
        nationality: player.nationality,
        birthplace: player.birthplace,
        height: player.height,
        weight: player.weight,
        bio: player.bio,
        season: season, // Lấy season từ key của đối tượng players
        playerType: player.playerType, // Giữ nguyên playerType
      });
    });
  });
  return acc;
}, []);

let stadiums = [
  {
    stadiumId: 1,
    stadiumName: "Hàng Đẫy",
    address: "Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội",
    capacity: 22500,
    standard: 5,
  },
  {
    stadiumId: 2,
    stadiumName: "Pleiku",
    address: "Đường Quang Trung, Phường Hội Thương, Thành phố Pleiku, Gia Lai",
    capacity: 12000,
    standard: 4,
  },
  {
    stadiumId: 3,
    stadiumName: "Gò Đậu",
    address: "Đường 30 Tháng 4, Phú Thọ, Thủ Dầu Một, Bình Dương",
    capacity: 18250,
    standard: 3,
  },
  {
    stadiumId: 4,
    stadiumName: "Lạch Tray",
    address: "Đường Chu Văn An, Đằng Giang, Ngô Quyền, Hải Phòng",
    capacity: 26000,
    standard: 4,
  },
  {
    stadiumId: 5,
    stadiumName: "Thanh Hóa",
    address: "Đại lộ Lê Lợi, Đông Hương, Thành phố Thanh Hóa, Thanh Hoá",
    capacity: 15000,
    standard: 3,
  },
  {
    stadiumId: 6,
    stadiumName: "Vinh",
    address: "Đường Lê Mao, Trường Thi, Thành phố Vinh, Nghệ An",
    capacity: 18000,
    standard: 3,
  },
  {
    stadiumId: 7,
    stadiumName: "Thiên Trường",
    address: "Đường Trần Anh Tông, Lộc Vượng, Thành phố Nam Định, Nam Định",
    capacity: 20000,
    standard: 3,
  },
];

// New data structure for matches
let matchesData = [
  {
    matchId: 1,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2023-08-05",
    time: "19:15",
    homeScore: 2,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Văn Quyết", team: 1, type: "penalty", time: "30'" },
      { player: "Geovane", team: 1, type: "own goal", time: "45'" },
      { player: "Tuấn Hải", team: 2, type: "normal", time: "75'" },
    ],
    cards: [
      { player: "Đỗ Hùng Dũng", team: 1, type: "Yellow", time: "60'" },
      { player: "Nguyễn Hoàng Đức", team: 2, type: "Yellow", time: "80'" },
    ],
  },
  {
    matchId: 2,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 3,
    awayTeamId: 4,
    date: "2023-08-06",
    time: "17:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 2,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Nguyễn Công Phượng", team: 3, type: "Yellow", time: "25'" },
    ],
  },
  {
    matchId: 3,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 5,
    awayTeamId: 6,
    date: "2023-08-06",
    time: "18:00",
    homeScore: 1,
    awayScore: 2,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { player: "Rimario Gordon", team: 5, type: "normal", time: "15'" },
      { player: "Bruno Cunha", team: 6, type: "normal", time: "50'" },
      { player: "Hữu Dũng", team: 6, type: "normal", time: "88'" },
    ],
    cards: [
      { player: "Hải Huy", team: 5, type: "Yellow", time: "35'" },
      { player: "Gustavo Santos", team: 6, type: "Yellow", time: "70'" },
    ],
  },
  {
    matchId: 4,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 7,
    awayTeamId: 8,
    date: "2023-08-07",
    time: "17:00",
    homeScore: 3,
    awayScore: 1,
    stadiumId: 6,
    isFinished: true,
    goals: [
      { player: "Olaha", team: 7, type: "normal", time: "10'" },
      { player: "Trần Đình Hoàng", team: 7, type: "normal", time: "55'" },
      { player: "Nguyễn Văn Toàn", team: 8, type: "normal", time: "65'" },
      { player: "Quế Ngọc Hải", team: 7, type: "penalty", time: "90+2'" },
    ],
    cards: [
      { player: "Phan Văn Đức", team: 7, type: "Yellow", time: "40'" },
      { player: "Đinh Viết Tú", team: 8, type: "Yellow", time: "78'" },
    ],
  },
  {
    matchId: 5,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 2,
    awayTeamId: 3,
    date: "2023-08-12",
    time: "19:15",
    homeScore: 1,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Jeferson Elias", team: 2, type: "normal", time: "20'" },
      { player: "Brandão", team: 3, type: "normal", time: "85'" },
    ],
    cards: [
      { player: "Nguyễn Đức Chiến", team: 2, type: "Yellow", time: "55'" },
      { player: "Tuấn Anh", team: 3, type: "Yellow", time: "68'" },
    ],
  },
  {
    matchId: 6,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 4,
    awayTeamId: 5,
    date: "2023-08-13",
    time: "17:00",
    homeScore: 2,
    awayScore: 0,
    stadiumId: 3,
    isFinished: true,
    goals: [
      { player: "Eydison", team: 4, type: "normal", time: "35'" },
      { player: "Vĩ Hào", team: 4, type: "normal", time: "70'" },
    ],
    cards: [
      { player: "Olivier Thil", team: 5, type: "Yellow", time: "48'" },
    ],
  },
  {
    matchId: 7,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 6,
    awayTeamId: 7,
    date: "2023-08-13",
    time: "18:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 5,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Đức Lợi", team: 6, type: "Yellow", time: "62'" },
      { player: "Xuân Mạnh", team: 7, type: "Yellow", time: "75'" },
    ],
  },
  {
    matchId: 8,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 8,
    awayTeamId: 1,
    date: "2023-08-14",
    time: "19:15",
    homeScore: 2,
    awayScore: 3,
    stadiumId: 7,
    isFinished: true,
    goals: [
      { player: "Hendrio", team: 8, type: "normal", time: "5'" },
      { player: "Lucao", team: 1, type: "normal", time: "18'" },
      { player: "Văn Quyết", team: 1, type: "normal", time: "40'" },
      { player: "Hendrio", team: 8, type: "penalty", time: "58'" },
      { player: "Marcao Silva", team: 1, type: "normal", time: "72'" },
    ],
    cards: [
      { player: "Khắc Ngọc", team: 8, type: "Yellow", time: "30'" },
      { player: "Duy Mạnh", team: 1, type: "Yellow", time: "45+1'" },
    ],
  },
  {
    matchId: 9,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1,
    awayTeamId: 3,
    date: "2023-08-19",
    time: "19:15",
    homeScore: null,
    awayScore: null,
    stadiumId: 1,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 10,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 2,
    awayTeamId: 4,
    date: "2023-08-20",
    time: "17:00",
    homeScore: null,
    awayScore: null,
    stadiumId: 1,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 11,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 5,
    awayTeamId: 7,
    date: "2023-08-20",
    time: "18:00",
    homeScore: null,
    awayScore: null,
    stadiumId: 4,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 12,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 6,
    awayTeamId: 8,
    date: "2023-08-21",
    time: "19:15",
    homeScore: null,
    awayScore: null,
    stadiumId: 5,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 13,
    season: "2022-2023",
    round: "2022-2023-ROUND1",
    homeTeamId: 1,
    awayTeamId: 5,
    date: "2022-08-05",
    time: "19:00",
    homeScore: 1,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Văn Quyết", team: 1, type: "normal", time: "55'" },
    ],
    cards: [
      { player: "Đỗ Hùng Dũng", team: 1, type: "Yellow", time: "70'" },
    ],
  },
  {
    matchId: 14,
    season: "2022-2023",
    round: "2022-2023-ROUND1",
    homeTeamId: 3,
    awayTeamId: 2,
    date: "2022-08-06",
    time: "17:00",
    homeScore: 2,
    awayScore: 2,
    stadiumId: 2,
    isFinished: true,
    goals: [
      { player: "Nguyễn Văn Toàn", team: 3, type: "normal", time: "15'" },
      { player: "Pedro Paulo", team: 2, type: "normal", time: "30'" },
      { player: "Nguyễn Công Phượng", team: 3, type: "normal", time: "60'" },
      { player: "Trần Danh Trung", team: 2, type: "normal", time: "80'" },
    ],
    cards: [
      { player: "Lương Xuân Trường", team: 3, type: "Yellow", time: "45'" },
      { player: "Bùi Tiến Dũng", team: 2, type: "Yellow", time: "75'" },
    ],
  },
  {
    matchId: 15,
    season: "2022-2023",
    round: "2022-2023-ROUND2",
    homeTeamId: 5,
    awayTeamId: 3,
    date: "2022-08-12",
    time: "18:00",
    homeScore: 0,
    awayScore: 1,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { player: "Brandão", team: 3, type: "normal", time: "25'" },
    ],
    cards: [
      { player: "Triệu Việt Hưng", team: 5, type: "Yellow", time: "35'" },
    ],
  },
  {
    matchId: 16,
    season: "2022-2023",
    round: "2022-2023-ROUND2",
    homeTeamId: 2,
    awayTeamId: 1,
    date: "2022-08-13",
    time: "19:15",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Nguyễn Hoàng Đức", team: 2, type: "Yellow", time: "50'" },
      { player: "Nguyễn Thành Chung", team: 1, type: "Yellow", time: "65'" },
    ],
  },
];
let typeSettings = {
  goalTypes: [
    { code: 'BT001', name: 'Bàn thắng thường', description: 'Bàn thắng được ghi trong tình huống thông thường.' },
    { code: 'BT002', name: 'Phản lưới nhà', description: 'Bàn thắng do cầu thủ tự đưa bóng vào lưới nhà.' },
    { code: 'BT003', name: 'Penalty', description: 'Bàn thắng từ chấm phạt đền.' },
  ],
  cardTypes: [
    { code: 'TP001', name: 'Vàng', description: 'Cảnh cáo cho hành vi phi thể thao.' },
    { code: 'TP002', name: 'Đỏ', description: 'Truất quyền thi đấu do lỗi nghiêm trọng.' },
  ],
  priorityOptions: [
    { code: 'UT1', name: 'Điểm số' },
    { code: 'UT2', name: 'Hiệu số' },
    { code: 'UT3', name: 'Số bàn thắng' },
  ],
  rankingPriorityOrder: ['UT1', 'UT2', 'UT3'],
};

module.exports = {
  availableTeams,
  seasons,
  players,
  availablePlayers,
  stadiums,
  matchesData,
  typeSettings
};