// --- START OF FILE data.js ---
const availableTeams = [
  {
    id: 1,
    name: "Hà Nội FC",
    city: "Hà Nội",
    coach: "Gad",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 5,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/e/eb/Hanoi_FC.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hà Nội",
    season: null,
  },
  {
    id: 2,
    name: "Viettel FC",
    city: "Hà Nội",
    coach: "Tăng Nhất",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 4,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/d/d5/Viettel_FC_logo.png/1200px-Viettel_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Viettel",
    season: null,
  },
  {
    id: 3,
    name: "Hoàng Anh Gia Lai",
    city: "Pleiku",
    coach: "Faigar",
    stadium: "Pleiku",
    stadiumId: 2,
    capacity: 12000,
    standard: 4,
    home_kit_image: null,
    away_kit_image: null,
    third_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/7/7d/Hoang_Anh_Gia_Lai_FC_logo.png/1200px-Hoang_Anh_Gia_Lai_FC_logo.png",
    description: "Câu lạc bộ bóng đá Hoàng Anh Gia Lai",
    season: null,
  },
  {
    id: 4,
    name: "Becamex Bình Dương",
    city: "Thủ Dầu Một",
    coach: "Superman",
    stadium: "Gò Đậu",
    stadiumId: 3,
    capacity: 18250,
    standard: 3,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/0/07/Becamex_Binh_Duong_FC_logo.png/1200px-Becamex_Binh_Duong_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Becamex Bình Dương",
    season: null,
  },
  {
    id: 5,
    name: "Hải Phòng",
    city: "Hải Phòng",
    coach: "tslnh",
    stadium: "Lạch Tray",
    stadiumId: 4,
    capacity: 26000,
    standard: 4,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/8/85/Hai_Phong_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hải Phòng",
    season: null,
  },
  {
    id: 6,
    name: "Đông Á Thanh Hóa",
    city: "Thanh Hóa",
    coach: "Popovic",
    stadium: "Thanh Hóa",
    stadiumId: 5,
    capacity: 15000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/e/e7/%C4%90%C3%B4ng_A_Thanh_H%C3%B3a_FC_logo.svg/1200px-%C4%90%C3%B4ng_A_Thanh_H%C3%B3a_FC_logo.svg.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Đông Á Thanh Hóa",
    season: null,
  },
  {
    id: 7,
    name: "Sông Lam Nghệ An",
    city: "Vinh",
    coach: "Phan Như Thuật",
    stadium: "Vinh",
    stadiumId: 6,
    capacity: 18000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/a/a8/Song_Lam_Nghe_An_FC_logo.png/1200px-Song_Lam_Nghe_An_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Sông Lam Nghệ An",
    season: null,
  },
  {
    id: 8,
    name: "Nam Định FC",
    city: "Nam Định",
    coach: "Vũ Hồng Việt",
    stadium: "Thiên Trường",
    stadiumId: 7,
    capacity: 20000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/c/c7/Nam_%C4%90%E1%BB%8Bnh_FC_logo.png/1200px-Nam_%C4%90%E1%BB%8Bnh_FC_logo.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Nam Định",
    season: null,
  },
];

const seasons = [
  {
    id: "2023-2024",
    name: "Mùa giải 2023-2024",
    startDate: "2023-08-01",
    endDate: "2024-05-30",
    teams: [1, 2, 3, 4, 5, 6, 7, 8],
    rounds: [
      {
        roundId: "2023-2024-ROUND1",
        name: "Lượt đi",
        startDate: "2023-08-05",
        endDate: "2023-08-07",
      },
      {
        roundId: "2023-2024-ROUND2",
        name: "Lượt về",
        startDate: "2023-08-12",
        endDate: "2023-08-14",
      },
    ],
  },
  {
    id: "2024-2025",
    name: "Mùa giải 2024-2025",
    startDate: "2024-08-01",
    endDate: "2025-05-30",
    teams: [1, 2, 3, 4, 5, 6, 7, 8],
    rounds: [],
  },
  {
    id: "2022-2023",
    name: "Mùa giải 2022-2023",
    startDate: "2022-08-01",
    endDate: "2023-05-30",
    teams: [1, 2, 3, 4, 5],
    rounds: [
      {
        roundId: "2022-2023-ROUND1",
        name: "Lượt đi",
        startDate: "2022-08-05",
        endDate: "2022-08-07",
      },
      {
        roundId: "2022-2023-ROUND2",
        name: "Lượt về",
        startDate: "2022-08-12",
        endDate: "2022-08-14",
      },
    ],
  },
];

const players = {
  "2023-2024": {
    1: [
      {
        id: 1,
        name: "Cầu thủ A1",
        dob: "1999-03-15",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 180,
        weight: 75,
        bio: "Một tiền đạo tài năng của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 4,
        name: "Cầu thủ A2",
        dob: "1997-07-22",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 178,
        weight: 72,
        bio: "Tiền vệ trung tâm, điều tiết trận đấu.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    2: [
      {
        id: 2,
        name: "Cầu thủ B2",
        dob: "1998-05-20",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Hồ Chí Minh",
        height: 175,
        weight: 70,
        bio: "Một hậu vệ chắc chắn.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 5,
        name: "Cầu thủ B3",
        dob: "2000-11-10",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "Rio de Janeiro",
        height: 185,
        weight: 80,
        bio: "Tiền đạo ngoại binh chất lượng.",
        season: "2023-2024",
        playerType: "Nước ngoài",
      },
    ],
    3: [
      {
        id: 6,
        name: "Cầu thủ C4",
        dob: "1996-09-01",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Gia Lai",
        height: 170,
        weight: 65,
        bio: "Tiền vệ cánh nhanh nhẹn.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    4: [
      {
        id: 7,
        name: "Cầu thủ D5",
        dob: "1995-04-18",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Bình Dương",
        height: 183,
        weight: 77,
        bio: "Trung vệ kinh nghiệm.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    5: [
      {
        id: 8,
        name: "Cầu thủ E6",
        dob: "1999-12-25",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hải Phòng",
        height: 179,
        weight: 74,
        bio: "Tiền đạo chủ lực của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    6: [
      {
        id: 9,
        name: "Cầu thủ F7",
        dob: "1994-06-03",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Thanh Hóa",
        height: 176,
        weight: 71,
        bio: "Tiền vệ phòng ngự mạnh mẽ.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    7: [
      {
        id: 10,
        name: "Cầu thủ G8",
        dob: "2001-02-14",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 181,
        weight: 76,
        bio: "Hậu vệ cánh đầy triển vọng.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    8: [
      {
        id: 11,
        name: "Cầu thủ H9",
        dob: "1993-08-30",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Nam Định",
        height: 184,
        weight: 79,
        bio: "Tiền đạo có khả năng ghi bàn tốt.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
  },
  "2022-2023": {
    1: [
      {
        id: 3,
        name: "Cầu thủ C3",
        dob: "1997-10-10",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Đà Nẵng",
        height: 182,
        weight: 78,
        bio: "Một tiền vệ sáng tạo.",
        season: "2022-2023",
        playerType: "Trong nước",
      },
      {
        id: 12,
        name: "Cầu thủ C5",
        dob: "1996-11-22",
        position: "Hậu vệ",
        nationality: "Hàn Quốc",
        birthplace: "Seoul",
        height: 184,
        weight: 80,
        bio: "Trung vệ ngoại binh chất lượng.",
        season: "2022-2023",
        playerType: "Nước ngoài",
      },
    ],
    2: [
      {
        id: 13,
        name: "Cầu thủ B4",
        dob: "1995-07-01",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Thái Bình",
        height: 177,
        weight: 73,
        bio: "Tiền đạo cánh nhanh nhẹn.",
        season: "2022-2023",
        playerType: "Trong nước",
      },
    ],
  },
};

// Khai báo availablePlayers - Danh sách cầu thủ có sẵn
const availablePlayers = [
  {
    id: 1,
    name: "Cầu thủ A1",
    dob: "1999-03-15",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 180,
    weight: 75,
    bio: "Một tiền đạo tài năng của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 2,
    name: "Cầu thủ B2",
    dob: "1998-05-20",
    position: "Hậu vệ",
    nationality: "Việt Nam",
    birthplace: "Hồ Chí Minh",
    height: 175,
    weight: 70,
    bio: "Một hậu vệ chắc chắn.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 3,
    name: "Cầu thủ C3",
    dob: "1997-10-10",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Đà Nẵng",
    height: 182,
    weight: 78,
    bio: "Một tiền vệ sáng tạo.",
    season: "2022-2023",
    playerType: "Trong nước",
  },
  {
    id: 4,
    name: "Cầu thủ A2",
    dob: "1997-07-22",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hải Dương",
    height: 178,
    weight: 72,
    bio: "Tiền vệ trung tâm, điều tiết trận đấu.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 5,
    name: "Cầu thủ B3",
    dob: "2000-11-10",
    position: "Tiền đạo",
    nationality: "Brazil",
    birthplace: "Rio de Janeiro",
    height: 185,
    weight: 80,
    bio: "Tiền đạo ngoại binh chất lượng.",
    season: "2023-2024",
    playerType: "Nước ngoài",
  },
  {
    id: 6,
    name: "Cầu thủ C4",
    dob: "1996-09-01",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Gia Lai",
    height: 170,
    weight: 65,
    bio: "Tiền vệ cánh nhanh nhẹn.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 7,
    name: "Cầu thủ D5",
    dob: "1995-04-18",
    position: "Hậu vệ",
    nationality: "Việt Nam",
    birthplace: "Bình Dương",
    height: 183,
    weight: 77,
    bio: "Trung vệ kinh nghiệm.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 8,
    name: "Cầu thủ E6",
    dob: "1999-12-25",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hải Phòng",
    height: 179,
    weight: 74,
    bio: "Tiền đạo chủ lực của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 9,
    name: "Cầu thủ F7",
    dob: "1994-06-03",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Thanh Hóa",
    height: 176,
    weight: 71,
    bio: "Tiền vệ phòng ngự mạnh mẽ.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 10,
    name: "Cầu thủ G8",
    dob: "2001-02-14",
    position: "Hậu vệ",
    nationality: "Việt Nam",
    birthplace: "Nghệ An",
    height: 181,
    weight: 76,
    bio: "Hậu vệ cánh đầy triển vọng.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 11,
    name: "Cầu thủ H9",
    dob: "1993-08-30",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Nam Định",
    height: 184,
    weight: 79,
    bio: "Tiền đạo có khả năng ghi bàn tốt.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 12,
    name: "Cầu thủ C5",
    dob: "1996-11-22",
    position: "Hậu vệ",
    nationality: "Hàn Quốc",
    birthplace: "Seoul",
    height: 184,
    weight: 80,
    bio: "Trung vệ ngoại binh chất lượng.",
    season: "2022-2023",
    playerType: "Nước ngoài",
  },
  {
    id: 13,
    name: "Cầu thủ B4",
    dob: "1995-07-01",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Thái Bình",
    height: 177,
    weight: 73,
    bio: "Tiền đạo cánh nhanh nhẹn.",
    season: "2022-2023",
    playerType: "Trong nước",
  },
];
const stadiums = [
  {
    stadiumId: 1,
    stadiumName: "Hàng Đẫy",
    address: "Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội",
    capacity: 22500,
    standard: 5,
  },
  {
    stadiumId: 2,
    stadiumName: "Pleiku",
    address: "Đường Quang Trung, Phường Hội Thương, Thành phố Pleiku, Gia Lai",
    capacity: 12000,
    standard: 4,
  },
  {
    stadiumId: 3,
    stadiumName: "Gò Đậu",
    address: "Đường 30 Tháng 4, Phú Thọ, Thủ Dầu Một, Bình Dương",
    capacity: 18250,
    standard: 3,
  },
  {
    stadiumId: 4,
    stadiumName: "Lạch Tray",
    address: "Đường Chu Văn An, Đằng Giang, Ngô Quyền, Hải Phòng",
    capacity: 26000,
    standard: 4,
  },
  {
    stadiumId: 5,
    stadiumName: "Thanh Hóa",
    address: "Đại lộ Lê Lợi, Đông Hương, Thành phố Thanh Hóa, Thanh Hoá",
    capacity: 15000,
    standard: 3,
  },
  {
    stadiumId: 6,
    stadiumName: "Vinh",
    address: "Đường Lê Mao, Trường Thi, Thành phố Vinh, Nghệ An",
    capacity: 18000,
    standard: 3,
  },
  {
    stadiumId: 7,
    stadiumName: "Thiên Trường",
    address: "Đường Trần Anh Tông, Lộc Vượng, Thành phố Nam Định, Nam Định",
    capacity: 20000,
    standard: 3,
  },
];

// New data structure for matches
const matchesData = [
  {
    matchId: 1,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1, // Reference to Hà Nội FC
    awayTeamId: 2, // Reference to Viettel FC
    date: "2023-08-05",
    time: "19:15",
    homeScore: 2,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Văn Quyết", team: "Hà Nội FC", type: "penalty", time: "30'" },
      { player: "Geovane", team: "Hà Nội FC", type: "own goal", time: "45'" },
      { player: "Tuấn Hải", team: "Viettel FC", type: "normal", time: "75'" },
    ],
    cards: [
      { player: "Hùng Dũng", team: "Hà Nội FC", type: "Yellow", time: "60'" },
      { player: "Hoàng Đức", team: "Viettel FC", type: "Yellow", time: "80'" },
    ],
  },
  {
    matchId: 2,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 3, // Reference to Hoàng Anh Gia Lai
    awayTeamId: 4, // Reference to Becamex Bình Dương
    date: "2023-08-06",
    time: "17:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 2,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Công Phượng", team: "Hoàng Anh Gia Lai", type: "Yellow", time: "25'" },
    ],
  },
  {
    matchId: 3,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 5, // Reference to Hải Phòng
    awayTeamId: 6, // Reference to Đông Á Thanh Hóa
    date: "2023-08-06",
    time: "18:00",
    homeScore: 1,
    awayScore: 2,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { player: "Rimario", team: "Hải Phòng", type: "normal", time: "15'" },
      { player: "Bruno Cunha", team: "Đông Á Thanh Hóa", type: "normal", time: "50'" },
      { player: "Hữu Dũng", team: "Đông Á Thanh Hóa", type: "normal", time: "88'" },
    ],
    cards: [
      { player: "Hải Huy", team: "Hải Phòng", type: "Yellow", time: "35'" },
      { player: "Gustavo Santos", team: "Đông Á Thanh Hóa", type: "Yellow", time: "70'" },
    ],
  },
  {
    matchId: 4,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 7, // Reference to Sông Lam Nghệ An
    awayTeamId: 8, // Reference to Nam Định FC
    date: "2023-08-07",
    time: "17:00",
    homeScore: 3,
    awayScore: 1,
    stadiumId: 6,
    isFinished: true,
    goals: [
      { player: "Olaha", team: "Sông Lam Nghệ An", type: "normal", time: "10'" },
      { player: "Trần Đình Hoàng", team: "Sông Lam Nghệ An", type: "normal", time: "55'" },
      { player: "Nguyễn Văn Toàn", team: "Nam Định FC", type: "normal", time: "65'" },
      { player: "Quế Ngọc Hải", team: "Sông Lam Nghệ An", type: "penalty", time: "90+2'" },
    ],
    cards: [
      { player: "Phan Văn Đức", team: "Sông Lam Nghệ An", type: "Yellow", time: "40'" },
      { player: "Đinh Viết Tú", team: "Nam Định FC", type: "Yellow", time: "78'" },
    ],
  },
  {
    matchId: 5,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 2, // Reference to Viettel FC
    awayTeamId: 3, // Reference to Hoàng Anh Gia Lai
    date: "2023-08-12",
    time: "19:15",
    homeScore: 1,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Jeferson Elias", team: "Viettel FC", type: "normal", time: "20'" },
      { player: "Brandão", team: "Hoàng Anh Gia Lai", type: "normal", time: "85'" },
    ],
    cards: [
      { player: "Nguyễn Đức Chiến", team: "Viettel FC", type: "Yellow", time: "55'" },
      { player: "Tuấn Anh", team: "Hoàng Anh Gia Lai", type: "Yellow", time: "68'" },
    ],
  },
  {
    matchId: 6,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 4, // Reference to Becamex Bình Dương
    awayTeamId: 5, // Reference to Hải Phòng
    date: "2023-08-13",
    time: "17:00",
    homeScore: 2,
    awayScore: 0,
    stadiumId: 3,
    isFinished: true,
    goals: [
      { player: "Eydison", team: "Becamex Bình Dương", type: "normal", time: "35'" },
      { player: "Vĩ Hào", team: "Becamex Bình Dương", type: "normal", time: "70'" },
    ],
    cards: [
      { player: "Olivier Thil", team: "Hải Phòng", type: "Yellow", time: "48'" },
    ],
  },
  {
    matchId: 7,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 6, // Reference to Đông Á Thanh Hóa
    awayTeamId: 7, // Reference to Sông Lam Nghệ An
    date: "2023-08-13",
    time: "18:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 5,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Đức Lợi", team: "Đông Á Thanh Hóa", type: "Yellow", time: "62'" },
      { player: "Xuân Mạnh", team: "Sông Lam Nghệ An", type: "Yellow", time: "75'" },
    ],
  },
  {
    matchId: 8,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 8, // Reference to Nam Định FC
    awayTeamId: 1, // Reference to Hà Nội FC
    date: "2023-08-14",
    time: "19:15",
    homeScore: 2,
    awayScore: 3,
    stadiumId: 7,
    isFinished: true,
    goals: [
      { player: "Hendrio", team: "Nam Định FC", type: "normal", time: "5'" },
      { player: "Lucao", team: "Hà Nội FC", type: "normal", time: "18'" },
      { player: "Văn Quyết", team: "Hà Nội FC", type: "normal", time: "40'" },
      { player: "Hendrio", team: "Nam Định FC", type: "penalty", time: "58'" }, { player: "Marcao Silva", team: "Hà Nội FC", type: "normal", time: "72'" },
    ],
    cards: [
      { player: "Khắc Ngọc", team: "Nam Định FC", type: "Yellow", time: "30'" },
      { player: "Duy Mạnh", team: "Hà Nội FC", type: "Yellow", time: "45+1'" },
    ],
  },
  {
    matchId: 9,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1,
    awayTeamId: 3,
    date: "2023-08-19",
    time: "19:15",
    homeScore: null,
    awayScore: null,
    stadiumId: 1,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 10,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 2,
    awayTeamId: 4,
    date: "2023-08-20",
    time: "17:00",
    homeScore: null,
    awayScore: null,
    stadiumId: 1,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 11,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 5,
    awayTeamId: 7,
    date: "2023-08-20",
    time: "18:00",
    homeScore: null,
    awayScore: null,
    stadiumId: 4,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 12,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 6,
    awayTeamId: 8,
    date: "2023-08-21",
    time: "19:15",
    homeScore: null,
    awayScore: null,
    stadiumId: 5,
    isFinished: false,
    goals: [],
    cards: [],
  },
  {
    matchId: 13,
    season: "2022-2023",
    round: "2022-2023-ROUND1",
    homeTeamId: 1,
    awayTeamId: 5,
    date: "2022-08-05",
    time: "19:00",
    homeScore: 1,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { player: "Văn Quyết", team: "Hà Nội FC", type: "normal", time: "55'" },
    ],
    cards: [
      { player: "Đỗ Hùng Dũng", team: "Hà Nội FC", type: "Yellow", time: "70'" },
    ],
  },
  {
    matchId: 14,
    season: "2022-2023",
    round: "2022-2023-ROUND1",
    homeTeamId: 3,
    awayTeamId: 2,
    date: "2022-08-06",
    time: "17:00",
    homeScore: 2,
    awayScore: 2,
    stadiumId: 2,
    isFinished: true,
    goals: [
      { player: "Nguyễn Văn Toàn", team: "Hoàng Anh Gia Lai", type: "normal", time: "15'" },
      { player: "Pedro Paulo", team: "Viettel FC", type: "normal", time: "30'" },
      { player: "Nguyễn Công Phượng", team: "Hoàng Anh Gia Lai", type: "normal", time: "60'" },
      { player: "Trần Danh Trung", team: "Viettel FC", type: "normal", time: "80'" },
    ],
    cards: [
      { player: "Lương Xuân Trường", team: "Hoàng Anh Gia Lai", type: "Yellow", time: "45'" },
      { player: "Bùi Tiến Dũng", team: "Viettel FC", type: "Yellow", time: "75'" },
    ],
  },
  {
    matchId: 15,
    season: "2022-2023",
    round: "2022-2023-ROUND2",
    homeTeamId: 5,
    awayTeamId: 3,
    date: "2022-08-12",
    time: "18:00",
    homeScore: 0,
    awayScore: 1,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { player: "Brandão", team: "Hoàng Anh Gia Lai", type: "normal", time: "25'" },
    ],
    cards: [
      { player: "Triệu Việt Hưng", team: "Hải Phòng", type: "Yellow", time: "35'" },
    ],
  },
  {
    matchId: 16,
    season: "2022-2023",
    round: "2022-2023-ROUND2",
    homeTeamId: 2,
    awayTeamId: 1,
    date: "2022-08-13",
    time: "19:15",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [],
    cards: [
      { player: "Nguyễn Hoàng Đức", team: "Viettel FC", type: "Yellow", time: "50'" },
      { player: "Nguyễn Thành Chung", team: "Hà Nội FC", type: "Yellow", time: "65'" },
    ],
  },
];
let typeSettings = {
  goalTypes: [
    { code: 'BT001', name: 'Bàn thắng thường', description: 'Bàn thắng được ghi trong tình huống thông thường.' },
    { code: 'BT002', name: 'Phản lưới nhà', description: 'Bàn thắng do cầu thủ tự đưa bóng vào lưới nhà.' },
    { code: 'BT003', name: 'Penalty', description: 'Bàn thắng từ chấm phạt đền.' },
  ],
  cardTypes: [
    { code: 'TP001', name: 'Vàng', description: 'Cảnh cáo cho hành vi phi thể thao.' },
    { code: 'TP002', name: 'Đỏ', description: 'Truất quyền thi đấu do lỗi nghiêm trọng.' },
  ],
  priorityOptions: [
    { code: 'UT1', name: 'Điểm số' },
    { code: 'UT2', name: 'Hiệu số' },
    { code: 'UT3', name: 'Số bàn thắng' },
  ],
  rankingPriorityOrder: ['UT1', 'UT2', 'UT3'],
};

module.exports = {
  availableTeams,
  seasons,
  players,
  availablePlayers,
  stadiums,
  matchesData,
  typeSettings
};